services:
  backend:
    build:
      context: ./backend
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      WEBHOOK_URI: ${WEBHOOK_URI}
      DATABASE_PATH: postgres://postgres:${POSTGRES_PASSWORD}@postgis:5432/wanderwell?sslmode=disable
      SERVER_PORT: ":3000"
      FRONTEND_URL: ${FRONTEND_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_KEY: ${SESSION_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        PUBLIC_API_URL: ${PUBLIC_API_URL}
        PUBLIC_TILE_SERVER_URL: ${PUBLIC_TILE_SERVER_URL}
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  postgis:
    image: postgis/postgis:18-3.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wanderwell
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgis-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wanderwell"]
      interval: 5s
      timeout: 3s
      retries: 10

  tileserver:
    image: maplibre/martin:latest
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgis:5432/wanderwell?sslmode=disable
    depends_on:
      postgis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgis-data:
